version: '3.8'

name: intake24-dietician-dev

services:
  auth-db:
    image: postgres:15-alpine
    container_name: intake24-dietician-auth-db
    restart: always
    env_file:
      - ../apps/auth/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_DB}
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db/data-auth-db:/var/lib/postgresql/data

volumes:
  data-auth-db:
