version: '3.8'

name: intake24-dietician-dev

services:
  i24-dietician-db:
    image: postgres:alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: on-failure:3

  pgweb:
    image: sosedoff/pgweb
    env_file:
      - ./.env
    depends_on:
      - i24-dietician-db
    environment:
      PGWEB_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@i24-dietician-db:5432/${DB_NAME}?sslmode=disable
    ports:
      - ${PGWEB_PORT}:8081
    restart: on-failure:3

  redis:
    image: redis:latest
    command: redis-server
    env_file:
      - ../apps/auth/.env.development
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    env_file:
      - ../apps/auth/.env.development
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis:
  redis-config:

networks:
  redis-network:
    driver: bridge
