version: '3.8'

name: intake24-dietician-dev

services:
  # main DB for the system
  i24-dietician-db:
    container_name: i24-dietician-db
    image: postgres:16-alpine # always specify ther exact version
    env_file:
      - ./.env
    networks:
      - backend
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT_NEW}:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ./data-db-new:/var/lib/postgresql/data
    restart: on-failure:3

  redis:
    image: redis:latest
    command: redis-server
    env_file:
      - ../apps/api/.env.development
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    env_file:
      - ../apps/api/.env.development
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis:
  redis-config:
  local_pgdata:

networks:
  backend:
  redis-network:
    driver: bridge
