version: '3.8'

name: intake24-dietician-dev

services:
  # main DB for the system
  i24-dietician-db:
    container_name: i24-dietician-db
    image: postgres:16-alpine # always specify ther exact version
    env_file:
      - ./.env
    networks:
      - backend
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: on-failure:3
  
  # Db for the storing recall Data
  i24-dietician-recall-db:
    container_name: i24-dietician-recall-db # always specify ther exact version
    image: mongo:7.0.2-jammy
    networks:
      - backend
    restart: unless-stopped
    ports:
      - '${MONGO_RECALL_DB_PORT}:27017'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME:${MONGO_RECAL_DB_ROOT_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD:${MONGO_RECAL_DB_ROOT_PASSWORD}'
    volumes:
      - ./mongo_db/db:/data/db
      # - ./init/mongo_db/init.sh:/init.sh
    # command: bash /init.sh

  pgweb:
    image: sosedoff/pgweb
    env_file:
      - ./.env
    depends_on:
      - i24-dietician-db
    environment:
      PGWEB_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@i24-dietician-db:${POSTGRES_PORT}/${DB_NAME}?sslmode=disable
    ports:
      - ${PGWEB_PORT}:8081
    restart: on-failure:3

  redis:
    image: redis:latest
    command: redis-server
    env_file:
      - ../apps/auth/.env.development
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    env_file:
      - ../apps/auth/.env.development
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis:
  redis-config:

networks:
  backend:
  redis-network:
    driver: bridge
